version: '3.8'

services:
  glassfish:
    build:
      context: .
      dockerfile: Dockerfile
    image: brrobotics-glassfish
    container_name: brrobotics-glassfish
    ports:
      - "9000:8080"
    networks:
      - brrobotics-network
    depends_on:
      - derby

  derby:
    image: az82/docker-derby
    container_name: derby-server
    ports:
      - "1527:1527"
    networks:
      - brrobotics-network

networks:
  brrobotics-network:
    driver: bridge
